AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:
  VpcCIDR:
    Type: String
  VpcName:
    Type: String
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    AllowedPattern: "^[a-z0-9.-]{3,63}$"
    ConstraintDescription: Bucket name must be lowercase, 3-63 characters, and can include hyphens or dots.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Ref VpcName

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName