AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:
  newusername:
    Type: String
  username:
    Type: String
  Rolename:
    Type: String

Resources:

  myUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref username
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  mynewUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref newusername
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  myRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Ref Rolename
      AssumeRolePolicyDocument: 
      Policies:
        - PolicyName: inlineS3ReadOnlyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                Resource: '*'