AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:
  VpcCIDR:
    Type: String
  VpcName:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Ref VpcName