AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:
  username:
    Type: String
    Description: Name of the S3 bucket
    AllowedPattern: "^[a-z0-9.-]$"
    ConstraintDescription: Bucket name must be lowercase, 3-63 characters, and can include hyphens or dots.

Resources:
  myUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref username
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

