AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:
  bucketname:
    Type: String

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketname