AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:

  username:
    Type: String

Resources:

  myUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref username
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  