name: Deploy sample resource to CloudFormation

on:
  push:
    branches:
      - dev

jobs:
  cloudformation-deploy:
    name: Deploy Cloudformation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} 

    - name: Set env BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
 
    - name: Set stack name and DEPLOYMENT_ENV
      run: |
         if [[ $BRANCH == 'master' || $BRANCH == 'main' ]]; then
          echo "DEPLOYMENT_ENV=prod" >> "$GITHUB_ENV"
          echo "STACK_NAME=prod-stack" >> "$GITHUB_ENV"
         elif [[ $BRANCH == 'qa' ]]; then
          echo "DEPLOYMENT_ENV=qa" >> "$GITHUB_ENV"
          echo "STACK_NAME=qa-stack" >> "$GITHUB_ENV"
         else
          echo "DEPLOYMENT_ENV=dev" >> "$GITHUB_ENV"
          echo "STACK_NAME=dev-demo" >> "$GITHUB_ENV"
         fi

    - name: Print all the variable parameters
      run: |
          echo "Deployment Stack Name : ${{ env.STACK_NAME }}"

    - name: Prepare Parameter Overrides
      id: prepare_params
      run: |
        params=$(cat ./params.${{ env.DEPLOYMENT_ENV }}.json | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join(" ")')
        echo "params=$params" >> $GITHUB_ENV

    - name: Install cfn-lint
      run: pip install cfn-lint
 
    - name: Print the CloudFormation Linter Version & Run Linter
      run: |
        cfn-lint --version
        cfn-lint --ignore-checks W3011,W3002 -t ./template.yml

        
    - name: Deploy to AWS Cloudformation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.STACK_NAME }}
        template:  ./template.yml
        parameter-overrides: file://${{ github.workspace }}/params.${{ env.DEPLOYMENT_ENV }}.json
        no-fail-on-empty-changeset: "1"
        